---
- name: Converge
  hosts: all
  roles:
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  vars:
    adjoin_domains:
      - { name: 'dom1.lab',
          workgroup: 'DOM1',
          domain_controllers: [
            'dc.dom1.lab',
          ],
          ldap_base_dn: 'dc=dom1,dc=lab',
          computer_objects_path: 'Molecule/Computers',
          linux_admins: 'Domain Admins',
          username: 'administrator',
          password: 'Password1@' }
      - { name: 'dom2.lab',
          workgroup: 'DOM2',
          domain_controllers: [
            'dc.dom2.lab',
          ],
          ldap_base_dn: 'dc=dom2,dc=lab',
          computer_objects_path: 'Molecule/Computers',
          linux_admins: 'Domain Admins',
          username: 'administrator',
          password: 'Password1@' }
